#! /bin/sh
#                               -*- Mode: Sh -*- 
# preinst --- 
# Author           : Manoj Srivastava ( srivasta@glaurung.green-gryphon.com ) 
# Created On       : Fri Oct 10 12:29:47 2003
# Created On Node  : glaurung.green-gryphon.com
# Last Modified By : Manoj Srivastava
# Last Modified On : Fri Oct 10 12:37:26 2003
# Last Machine Used: glaurung.green-gryphon.com
# Update Count     : 3
# Status           : Unknown, Use with caution!
# HISTORY          : 
# Description      : 
# 
# 


# Abort if any command returns an error value
set -e

# This script is called before this version of this package is installed.
# When this script is called, the package's files have not been unpacked
# yet.


statedir='/var/lib/ucf';
package_name=ucf

if [ -z "$package_name" ]; then
    print >&2 "Internal Error. Please report a bug."
    exit 1;
fi

case "$1" in
  install)
    # About to install this package.
    :

    # Add a diversion.  This is one of the few things which may be done
    # before installing any files from the package.
    

    # There are two sub-cases:
    if test "${2+set}" = set; then
      # The configuration files from version $2 of this package are
      # still on the system.
      :
      echo >&2 "Moving old data out of the way"
      for i in $(/usr/bin/seq 6 -1 0); do
	  if [ -e "${statedir}/hashfile.${i}" ]; then
	      cp -f "${statedir}/hashfile.${i}" \
		  "${statedir}/hashfile.$(($i+1))"
	  fi 
      done
      if [ -e "$statedir/hashfile" ]; then
	  cp -f "$statedir/hashfile"  "$statedir/hashfile.0" 
      fi

    else
      # There is no existing configuration; install from scratch.
      :

    fi ;;
  upgrade)
    # About to upgrade this package from version $2 TO THIS VERSION.
    # "prerm upgrade" has already been called for the old version of
    # this package.
    :

    ;;
  abort-upgrade)
    # Back out of an attempt to upgrade this package FROM THIS VERSION to
    # version $2.  Undo the effects of "postrm upgrade $2".
    :

    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 0;;
esac

exit 0
